server.port=8085

spring.application.name=forohub


spring.datasource.url=jdbc:mysql://localhost:3306/foro_hubdb
spring.datasource.username=root
spring.datasource.password={DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

api.security.token=${JWT_SECRET:12345678}